[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "machine.json"

[target.'cfg(target_pointer_width = "32")']
rustflags = [
  "-Clink-args=-Tmachine.ld",
]

[target.'cfg(target_pointer_width = "64")']
runner = "qemu-system-riscv64 -machine virt -bios none -m 256M -smp 1 -global virtio-mmio.force-legacy=false -serial stdio -device virtio-blk-device,drive=hd0,bus=virtio-mmio-bus.0 -device virtio-gpu-device,bus=virtio-mmio-bus.1 -device virtio-mouse-device,bus=virtio-mmio-bus.2 -device virtio-keyboard-device,bus=virtio-mmio-bus.3 -drive file=disk.img,format=raw,id=hd0 -kernel "
rustflags = [
  "-Clink-args=-Tmachine.ld",
]
