[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "machine.json"

[target.'cfg(target_pointer_width = "32")']
rustflags = [
  "-Clink-args=-Tmachine.ld",
]

[target.'cfg(target_pointer_width = "64")']
rustflags = [
  "-Clink-args=-Tmachine.ld",
]
